version: '3.4'

services:
  catalog.db:
    container_name: catalog.db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://catalog.db:27017
    depends_on: 
      - catalog.db
    ports:
      - 8000:80
